name: mlx-app
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.13.2
  # Machine Learning
  - pytorch=2.6
  - torchvision=0.21.0
  - scikit-learn=1.6.1
  # Web UI
  - streamlit=1.44.0
  - pip
  - pip:
    - streamlit-drawable-canvas==0.9.3
  # Database
  - psycopg=3.2.6
  # Image Processing
  - pillow=10.1.0
  - numpy=1.26.3
  # API
  - fastapi=0.112.2
  - uvicorn=0.32.1
  - pydantic-settings=2.8.1
  # Configuration
  - python-dotenv=1.0.0
  # Development tools
  - black=24.3.0
  - isort=5.13.2
  - mypy=1.8.0 
  - pytest=8.3.4
  - httpx=0.27.0
  - flake8=7.0.0