name: mlx-app
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  # Machine Learning
  - pytorch=2.2
  - torchvision=0.17.0
  - scikit-learn=1.4.0
  # Web UI
  - streamlit=1.32.0
  - pip
  - pip:
    - streamlit-drawable-canvas==0.9.3
  # Database
  - psycopg=3.1.12
  # Image Processing
  - pillow=10.1.0
  - numpy=1.26.0
  # API
  - fastapi=0.109.0
  - uvicorn=0.27.0
  - pydantic-settings=2.1.0
  # Configuration
  - python-dotenv=1.0.0
  # Development tools
  - black=24.1.0
  - isort=5.12.0
  - mypy=1.8.0 
  - pytest=7.4.0
  - httpx=0.25.0
  - flake8=7.0.0