name: mlx-app
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10
  # Machine Learning
  - pytorch=2.6.0
  - torchvision=0.21.0
  # Web UI
  - streamlit=1.32.2
  - pip
  - pip:
    - streamlit-drawable-canvas==0.9.3
  # Database
  - psycopg2=2.9.9
  # Image Processing
  - pillow=10.1.0
  - numpy=1.26.3
  # Configuration
  - python-dotenv=1.0.0
  # Development tools
  - flake8=7.0.0
  - black=24.3.0
  - isort=5.13.2
  - mypy=1.8.0
  - pytest=8.0.0